config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :bookmarks, only: [:index, :new]
  resources :albums, only: [:create] do
    collection do
      get :search
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookmarks do
        member do
          post :like
        end
      end
    end
  end
  get '/auth/spotify/callback', to: 'users#spotify'
end

app/models/album.rb
require 'open-uri'

class Album < ApplicationRecord
  belongs_to :artist
  has_many :bookmarks, dependent: :destroy
  validates :name, presence: true
  has_one_attached :photo
  accepts_nested_attributes_for :artist

  def attributes
    {
      id: nil,
      name: nil,
      release_date: nil,
      photo_url: photo_url,
      artist: nil
    }
  end

  def upload_photo(url)
    file = URI.open(url)
    photo.attach(io: file, filename: 'album.png', content_type: 'image/png')
  end

  def photo_url
    Cloudinary::Utils.cloudinary_url(photo.key)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
  validates :name, presence: true

  def attributes
    { id: nil, name: nil }
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  include ActiveModel::Serialization
  belongs_to :user
  belongs_to :album
  validates :album, uniqueness: { scope: :user }
  acts_as_votable
  acts_as_taggable_on :tags
  accepts_nested_attributes_for :album

  def attributes
    { id: nil, tag_list: nil, album: nil, cached_votes_total: nil }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookmarks
  has_many :taggings, through: :bookmarks
  has_many :tags, through: :taggings
  has_many :albums, through: :bookmarks
  has_many :artists, through: :albums
  has_one_attached :photo
  acts_as_voter

  def tag_list
    tags.pluck(:name).uniq
  end

  def self.find_for_spotify_oauth(request)
    # RSpotify::authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_CLIENT_SECRET'])
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    user_params = {
      provider: 'spotify',
      email: spotify_user.email,
      token: spotify_user.credentials.token,
      picture_url: spotify_user.images&.first&.url,
      spotify_id: spotify_user.id,
      name: spotify_user.display_name
    }
    user = User.find_by(provider: 'spotify', spotify_id: spotify_user.id)
    user ||= User.find_by(email: spotify_user.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
    return user
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  skip_after_action :verify_authorized, only: [:search]

  def search
    RSpotify::authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_CLIENT_SECRET'])
    @albums = RSpotify::Album.search(params[:query])
  end

  def create
    @album = Album.find_by(spotify_id: album_params[:spotify_id]) || Album.new(album_params)
    authorize @album
    if @album.save
      @album.upload_photo(params[:album][:photo_url])
      @bookmark = Bookmark.create(user: current_user, album: @album)
      # params[:tags].each do |tag|
      #   @bookmark.tag_list.add(tag) unless tag.blank?
      # end
      @bookmark.tag_list.add(params[:tags]) if params[:tags].present?
      @bookmark.tag_list.add(params[:tag_list], parse: true) if params[:tag_list].present?
      @bookmark.save
      redirect_to bookmarks_path
    else
      render 'bookings/new'
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :spotify_id, :release_date, artist_attributes: [:name])
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    if params[:tag].present?
      @bookmarks = policy_scope(Bookmark).tagged_with(params[:tag]).includes(:album).to_json
      @favs = [].to_json
      @new_ones = [].to_json
      @throw_backs = [].to_json
      @recents = [].to_json
      @tag = params[:tag]
    else
      @bookmarks = policy_scope(Bookmark).includes(:album)
      @favs = @bookmarks.order(cached_votes_total: :desc).to_json
      @new_ones = @bookmarks.order(created_at: :desc).to_json
      @throw_backs = @bookmarks.order(cached_votes_total: :asc).to_json
      @recents = @bookmarks.where('cached_votes_total >= ?', 1).order(updated_at: :desc).to_json
      @bookmarks = @bookmarks.to_json
    end
  end

  def new
    @bookmark = Bookmark.new
    @album = Album.new
    @album.build_artist
    authorize @bookmark
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @bookmarks = policy_scope(Bookmark).includes(:album).to_json
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  before_action :check_signed_in

  def home
  end

  private

  def check_signed_in
    redirect_to bookmarks_path if signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Devise::Controllers::Rememberable
  skip_before_action :authenticate_user!, only: [:spotify]
  skip_after_action :verify_authorized, only: [:spotify]

  def spotify
    user = User.find_for_spotify_oauth(request)
    if user.persisted?
      remember_me(user)
      sign_in_and_redirect user, event: :authentication
      flash[:notice] = "Signed in with Spotify"
    else
      session['devise.spotify_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/albums/_suggestions.html.erb
<div class="d-flex scroll-cards">
  <% albums.each do |album| %>
    <div class="card-product mx-2"
      data-action="click->album-add#fillForm"
      data-album-name="<%= album.name %>"
      data-artist-name="<%= album.artists&.first&.name %>"
      data-spotify-id="<%= album.id %>"
      data-release-date="<%= album.release_date %>"
      data-photo-url="<%= album.images&.first['url'] %>"
      data-album-add-target="card"
      >
      <%= image_tag album.images&.first['url'] %>
      <div class="card-product-infos">
        <h2><%= album.artists&.first&.name %></h2>
        <p><%= album.name %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/search.js.erb
document.getElementById('new_album').classList.add('d-none')
document.getElementById('album-suggestions').innerHTML =
'<%= j render "albums/suggestions", albums: @albums %>';

app/views/bookmarks/index.html.erb
<div id="root"
  data-controller='react-connect'
  data-bookmarks="<%= @bookmarks %>"
  data-favs="<%= @favs %>"
  data-new-ones="<%= @new_ones %>"
  data-throw-backs="<%= @throw_backs %>"
  data-recents="<%= @recents %>"
  data-tag="<%= @tag&.capitalize %>"
  data-user="<%= current_user.to_json %>"
>
</div>
<%# Add Stimulus to connect to React! %>

app/views/bookmarks/new.html.erb
<div class="container" data-controller='album-add'>
  <div class="row mt-5">
    <div class="col">
      <h1>Add Album</h1>
      <%= form_tag search_albums_path, remote: true, method: :get do %>
        <div class="search-form-control form-group">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for artist or album"
          %>
          <button name="button" type="submit" class="btn btn-warning">
            <i class="fas fa-search"></i>
          </button>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col" id='album-suggestions'>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= simple_form_for @album, html: { class: 'd-none', data: { album_add_target: 'form' }} do |f| %>
        <div class="mb-3 string optional album_tag_list">
          <label class="form-label string optional" for="album_tag_list">Add tags</label>
          <fieldset class="form-group check_boxes optional snippet_tags">
            <input type="hidden" name="tags[]" value="" />
            <% current_user.tag_list.each do |tag| %>
              <div class="tag-item">
                <input class="form-check-input check_boxes optional tag-selector" type="checkbox" value="<%= tag %>" name="tags][]" id="snippet_tag_ids_<%= tag %>">
                <label class="form-check-label collection_check_boxes" for="snippet_tag_ids_<%= tag %>"><%= tag %></label>
              </div>
            <% end %>
          </fieldset>
          <input class="form-control string optional mt-2 border-purple" type="text" value="" name="tag_list" id="album_tag_list">
          <div class="form-text">Or add your tags, separated by commas</div>
        </div>
        <%= f.input :name, as: :hidden, input_html: { data: { album_add_target: 'album_name' } } %>
        <%= f.input :release_date, as: :hidden, input_html: { data: { album_add_target: 'release_date' } } %>
        <%= f.input :spotify_id, as: :hidden, input_html: { data: { album_add_target: 'spotify_id' } } %>
        <%= hidden_field_tag 'album[photo_url]', nil, data: { album_add_target: 'photo_url' } %>
        <%= f.simple_fields_for :artist do |art_form| %>
          <%= art_form.input :name, as: :hidden, input_html: { data: { album_add_target: 'artist_name' } } %>
        <% end %>
        <%= f.submit 'Add', class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar_top' %>
    <%= render 'shared/flashes' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'shared/navbar_bottom' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jambox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar_top' %>
    <%= render 'shared/flashes' %>
    <div class="content">
      <div class="container">
        <div class="row justify-content-center mt-5">
          <div class="col col-sm-10 col-md-8 col-lg-6">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/navbar_bottom' %>
  </body>
</html>

app/views/lists/index.html.erb
<div id="root"
  data-bookmarks="<%= @bookmarks %>"
  data-user="<%= current_user.to_json %>"
>
</div>

app/views/pages/home.html.erb
<div id="root">
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar_bottom.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-bottom fixed-bottom">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= link_to bookmarks_path, class: "nav-link nav-link-custom d-flex align-items-center" do %>
        <i class="fas fa-user link-large"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "nav-link nav-link-custom d-flex align-items-center" do %>
        <i class="fas fa-user link-large"></i>
      <% end %>
    <% end %>
    <%= link_to bookmarks_path, class: "nav-link nav-link-custom btn-music" do %>
      <%= image_tag 'icon_no_bg.png', class: 'w-100' %>
    <% end %>
    <%= link_to new_bookmark_path, class: "nav-link nav-link-custom d-flex align-items-center" do %>
      <i class="fas fa-plus-square link-large"></i>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_top.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_no_bg.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Music", bookmarks_path, class: "nav-link nav-link-custom me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add", new_bookmark_path, class: "nav-link nav-link-custom me-2" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% elsif current_user.photo_url %>
              <%= image_tag current_user.photo_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "icon_black.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link nav-link-custom" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>